"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";
import { captureRequiredLocation, CapturedLocation } from "@/lib/geolocation";

const departments=["Amazonas","Antioquia","Arauca","Atlántico","Bogotá D.C.","Bolívar","Boyacá","Caldas","Caquetá","Casanare","Cauca","Cesar","Chocó","Córdoba","Cundinamarca","Guainía","Guaviare","Huila","La Guajira","Magdalena","Meta","Nariño","Norte de Santander","Putumayo","Quindío","Risaralda","San Andrés y Providencia","Santander","Sucre","Tolima","Valle del Cauca","Vaupés","Vichada"];

export default function Registrar(){
 const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false); const [locating,setLocating]=useState(false); const router=useRouter(); const [coords,setCoords]=useState<CapturedLocation|null>(null);
 async function locate(){setLocating(true);setMsg("Solicitando ubicación del dispositivo...");try{const location=await captureRequiredLocation();setCoords(location);setMsg(`Ubicación capturada. Precisión aproximada: ${Math.round(location.accuracy)} m.`);}catch(error){setCoords(null);setMsg(error instanceof Error?error.message:"No fue posible obtener la ubicación GPS.");}finally{setLocating(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!coords){setMsg("La ubicación GPS es obligatoria. Pulsa “Capturar ubicación GPS” y permite el acceso antes de guardar.");return;}setBusy(true);setMsg(""); const f=new FormData(e.currentTarget); const supabase=createClient(); if(!supabase){setMsg("No se pudo conectar con Supabase.");setBusy(false);return}
   const {data:{user}}=await supabase.auth.getUser(); if(!user){router.push("/auth");return;}
   const {error}=await supabase.from("collection_points").insert({owner_id:user.id,name:f.get("name"),department:f.get("department"),city:f.get("city"),address:f.get("address"),contact_name:f.get("contact_name"),contact_phone:f.get("contact_phone"),payment_alias:f.get("payment_alias"),payment_instructions:f.get("payment_instructions"),description:f.get("description"),latitude:coords.lat,longitude:coords.lng,location_accuracy_m:coords.accuracy,location_captured_at:coords.capturedAt});
   if(error)setMsg(error.message);else{setMsg("Punto registrado con ubicación GPS. Ahora puedes administrar donaciones y envíos.");setTimeout(()=>router.push("/dashboard"),700)} setBusy(false);
 }
 return <div className="panel"><Link href="/">← Inicio</Link><h1>Registrar punto de acopio</h1><p className="lead">Colombia es el país operativo principal. La ubicación GPS es obligatoria para registrar un punto y fortalecer la trazabilidad.</p><div className="notice">Las cuentas, teléfonos, dirección exacta y coordenadas se almacenan como datos operativos privados. La consulta pública solo presenta información sanitizada.</div><form className="card form-grid" style={{marginTop:18}} onSubmit={submit}>
 <div className="field"><label>Nombre del punto</label><input name="name" required placeholder="Centro de Acopio La Esperanza"/></div><div className="field"><label>Departamento</label><select name="department" required defaultValue=""><option value="" disabled>Selecciona</option>{departments.map(d=><option key={d}>{d}</option>)}</select></div><div className="field"><label>Ciudad / municipio</label><input name="city" required /></div><div className="field"><label>País</label><input value="Colombia" disabled readOnly /></div><div className="field full"><label>Dirección</label><input name="address" required /></div><div className="field"><label>Responsable</label><input name="contact_name" required/></div><div className="field"><label>Teléfono</label><input name="contact_phone" required/></div><div className="field full"><label>Dato para aportes monetarios</label><input name="payment_alias" placeholder="Llave, cuenta o enlace de pago"/></div><div className="field full"><label>Instrucciones para aportar</label><textarea name="payment_instructions" placeholder="Banco, tipo de cuenta o instrucciones. Evita publicar datos personales innecesarios."/></div><div className="field full"><label>Descripción / necesidades</label><textarea name="description"/></div>
 <div className="field full gps-box"><strong>Ubicación GPS obligatoria</strong><p>Activa los Servicios de ubicación del teléfono y permite el acceso a este sitio. La precisión también quedará registrada.</p><button type="button" className="btn btn-light" onClick={locate} disabled={locating}>{locating?"Obteniendo GPS...":coords?"Actualizar ubicación GPS":"Capturar ubicación GPS"}</button>{coords&&<div className="gps-success">✓ GPS capturado · precisión aprox. {Math.round(coords.accuracy)} m</div>}</div>
 <div className="field full"><button className="btn btn-primary" disabled={busy||locating||!coords}>{busy?"Guardando...":"Guardar punto de acopio"}</button>{msg&&<p className="form-message">{msg}</p>}</div></form></div>}
