"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";

const departments=["Amazonas","Antioquia","Arauca","Atlántico","Bogotá D.C.","Bolívar","Boyacá","Caldas","Caquetá","Casanare","Cauca","Cesar","Chocó","Córdoba","Cundinamarca","Guainía","Guaviare","Huila","La Guajira","Magdalena","Meta","Nariño","Norte de Santander","Putumayo","Quindío","Risaralda","San Andrés y Providencia","Santander","Sucre","Tolima","Valle del Cauca","Vaupés","Vichada"];
export default function Registrar(){
 const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false); const router=useRouter(); const [coords,setCoords]=useState<{lat:number;lng:number}|null>(null);
 function locate(){navigator.geolocation?.getCurrentPosition(p=>setCoords({lat:p.coords.latitude,lng:p.coords.longitude}),()=>setMsg("No fue posible obtener la ubicación. Puedes continuar sin GPS."),{enableHighAccuracy:true});}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg(""); const f=new FormData(e.currentTarget); const supabase=createClient(); if(!supabase){setMsg("No se pudo conectar con Supabase.");setBusy(false);return}
   const {data:{user}}=await supabase.auth.getUser(); if(!user){router.push("/auth");return;}
   const {error}=await supabase.from("collection_points").insert({owner_id:user.id,name:f.get("name"),department:f.get("department"),city:f.get("city"),address:f.get("address"),contact_name:f.get("contact_name"),contact_phone:f.get("contact_phone"),payment_alias:f.get("payment_alias"),payment_instructions:f.get("payment_instructions"),description:f.get("description"),latitude:coords?.lat??null,longitude:coords?.lng??null});
   if(error)setMsg(error.message);else{setMsg("Punto registrado. Ahora puedes administrar donaciones y envíos.");setTimeout(()=>router.push("/dashboard"),700)} setBusy(false);
 }
 return <div className="panel"><Link href="/">← Inicio</Link><h1>Registrar punto de acopio</h1><p className="lead">Colombia es el país operativo principal. Registra la ubicación y los datos necesarios para coordinar la ayuda.</p><div className="notice">Las cuentas, teléfonos, dirección exacta y coordenadas se almacenan como datos operativos privados. La consulta pública solo presenta información sanitizada.</div><form className="card form-grid" style={{marginTop:18}} onSubmit={submit}>
 <div className="field"><label>Nombre del punto</label><input name="name" required placeholder="Centro de Acopio La Esperanza"/></div><div className="field"><label>Departamento</label><select name="department" required defaultValue=""><option value="" disabled>Selecciona</option>{departments.map(d=><option key={d}>{d}</option>)}</select></div><div className="field"><label>Ciudad / municipio</label><input name="city" required /></div><div className="field"><label>País</label><input value="Colombia" disabled readOnly /></div><div className="field full"><label>Dirección</label><input name="address" required /></div><div className="field"><label>Responsable</label><input name="contact_name" required/></div><div className="field"><label>Teléfono</label><input name="contact_phone" required/></div><div className="field full"><label>Dato para aportes monetarios</label><input name="payment_alias" placeholder="Llave, cuenta o enlace de pago"/></div><div className="field full"><label>Instrucciones para aportar</label><textarea name="payment_instructions" placeholder="Banco, tipo de cuenta o instrucciones. Evita publicar datos personales innecesarios."/></div><div className="field full"><label>Descripción / necesidades</label><textarea name="description"/></div>
 <div className="field full"><button type="button" className="btn btn-light" onClick={locate}>{coords?`GPS capturado (${coords.lat.toFixed(5)}, ${coords.lng.toFixed(5)})`:"Capturar ubicación GPS"}</button></div>
 <div className="field full"><button className="btn btn-primary" disabled={busy}>{busy?"Guardando...":"Guardar punto de acopio"}</button>{msg&&<p className="form-message">{msg}</p>}</div></form></div>}
