"use client";
import Link from "next/link";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";

type Point={id:string;name:string;city:string;department:string;verified:boolean};
type Batch={id:string;public_code:string;received_at:string;donation_items?:Array<{id:string;item_name:string;category:string;quantity:number;unit:string}>};
type Shipment={id:string;public_code:string;status:string;destination_name:string;destination_city:string;destination_department:string;departure_at:string|null;delivered_at:string|null};
const statusLabel:Record<string,string>={preparing:"Preparando",ready:"Listo",in_transit:"En tránsito",delivered:"Entregado",cancelled:"Cancelado"};

export default function Dashboard(){
 const router=useRouter(); const [userId,setUserId]=useState(""); const [points,setPoints]=useState<Point[]>([]); const [pointId,setPointId]=useState(""); const [batches,setBatches]=useState<Batch[]>([]); const [shipments,setShipments]=useState<Shipment[]>([]); const [expenses,setExpenses]=useState<any[]>([]); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false); const [deliveryFiles,setDeliveryFiles]=useState<Record<string,File|null>>({});
 const point=useMemo(()=>points.find(p=>p.id===pointId),[points,pointId]);
 async function load(){const supabase=createClient();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/auth");return;}setUserId(user.id);
   const p=await supabase.from("collection_points").select("id,name,city,department,verified").order("created_at"); const ps=(p.data||[]) as Point[];setPoints(ps);const selected=pointId||ps[0]?.id||"";setPointId(selected);
   if(selected){const [b,s,e]=await Promise.all([supabase.from("donation_batches").select("id,public_code,received_at,donation_items(id,item_name,category,quantity,unit)").eq("collection_point_id",selected).order("created_at",{ascending:false}),supabase.from("shipments").select("id,public_code,status,destination_name,destination_city,destination_department,departure_at,delivered_at").eq("collection_point_id",selected).order("created_at",{ascending:false}),supabase.from("expenses").select("id,description,amount,currency,purchased_at,invoice_path").eq("collection_point_id",selected).order("created_at",{ascending:false})]);setBatches((b.data||[]) as Batch[]);setShipments((s.data||[]) as Shipment[]);setExpenses(e.data||[])}else{setBatches([]);setShipments([]);setExpenses([])}}
 useEffect(()=>{load()},[]); useEffect(()=>{if(userId&&pointId)load()},[pointId]);
 async function logout(){const supabase=createClient();await supabase?.auth.signOut();router.push("/")}
 async function createDonation(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!pointId)return;setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const supabase=createClient()!;const batch=await supabase.from("donation_batches").insert({collection_point_id:pointId,received_by:userId,donor_reference:f.get("donor_reference")||null,notes:f.get("notes")||null}).select("id,public_code").single();if(batch.error){setMsg(batch.error.message);setBusy(false);return;}const item=await supabase.from("donation_items").insert({donation_batch_id:batch.data.id,category:f.get("category"),item_name:f.get("item_name"),quantity:Number(f.get("quantity")),unit:f.get("unit")});if(item.error)setMsg(item.error.message);else{setMsg(`Donación registrada. Código para el donante: ${batch.data.public_code}`);e.currentTarget.reset();await load()}setBusy(false)}
 async function addInventory(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!pointId)return;setBusy(true);const f=new FormData(e.currentTarget);const supabase=createClient()!;const r=await supabase.from("inventory_items").insert({collection_point_id:pointId,category:f.get("category"),item_name:f.get("item_name"),quantity:Number(f.get("quantity")),unit:f.get("unit"),notes:f.get("notes")||null,created_by:userId});setMsg(r.error?r.error.message:"Inventario registrado.");if(!r.error)e.currentTarget.reset();setBusy(false)}
 async function addExpense(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!pointId)return;setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const supabase=createClient()!;const file=f.get("invoice") as File;let path:string|null=null;if(file&&file.size){path=`${userId}/${pointId}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await supabase.storage.from("invoice-receipts").upload(path,file);if(up.error){setMsg(up.error.message);setBusy(false);return;}}const r=await supabase.from("expenses").insert({collection_point_id:pointId,created_by:userId,description:f.get("description"),vendor_name:f.get("vendor_name")||null,amount:Number(f.get("amount")),invoice_path:path,purchased_at:f.get("purchased_at")||new Date().toISOString()});setMsg(r.error?r.error.message:"Gasto y comprobante registrados.");if(!r.error){e.currentTarget.reset();await load()}setBusy(false)}
 const donationItems=useMemo(()=>batches.flatMap(b=>(b.donation_items||[]).map(i=>({...i,batch_code:b.public_code}))),[batches]);
 async function createShipment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!pointId)return;setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const supabase=createClient()!;const dep=String(f.get("departure_at")||"");const r=await supabase.from("shipments").insert({collection_point_id:pointId,created_by:userId,destination_name:f.get("destination_name"),destination_department:f.get("destination_department"),destination_city:f.get("destination_city"),departure_at:dep?new Date(dep).toISOString():null,status:"ready"}).select("id,public_code").single();if(r.error){setMsg(r.error.message);setBusy(false);return;}const itemId=String(f.get("donation_item_id")||"");if(itemId){const q=Number(f.get("allocation_quantity"));const a=await supabase.from("donation_allocations").insert({donation_item_id:itemId,shipment_id:r.data.id,quantity:q});if(a.error){setMsg(`Envío creado (${r.data.public_code}), pero no se pudo vincular la donación: ${a.error.message}`);setBusy(false);await load();return;}}await supabase.from("status_events").insert({shipment_id:r.data.id,status:"ready",created_by:userId,note:"Envío preparado en el punto de acopio."});setMsg(`Envío creado: ${r.data.public_code}`);e.currentTarget.reset();await load();setBusy(false)}
 async function markDeparture(s:Shipment){setBusy(true);setMsg("");const supabase=createClient()!;const now=new Date().toISOString();const up=await supabase.from("shipments").update({status:"in_transit",departure_at:s.departure_at||now}).eq("id",s.id);if(!up.error)await supabase.from("status_events").insert({shipment_id:s.id,status:"in_transit",created_by:userId,note:"El cargamento salió hacia el destino."});setMsg(up.error?up.error.message:"Salida registrada. El seguimiento público ya muestra el envío en tránsito.");await load();setBusy(false)}
 async function deliver(s:Shipment){const file=deliveryFiles[s.id];if(!file){setMsg("Selecciona una fotografía de entrega antes de confirmar.");return;}setBusy(true);setMsg("Obteniendo ubicación GPS...");navigator.geolocation.getCurrentPosition(async pos=>{const supabase=createClient()!;const path=`${userId}/${s.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await supabase.storage.from("delivery-evidence").upload(path,file);if(up.error){setMsg(up.error.message);setBusy(false);return;}const now=new Date().toISOString();const ev=await supabase.from("delivery_evidence").insert({shipment_id:s.id,created_by:userId,evidence_type:"delivery_photo",storage_path:path,latitude:pos.coords.latitude,longitude:pos.coords.longitude,captured_at:now,note:"Entrega confirmada con evidencia fotográfica y ubicación GPS."});if(ev.error){setMsg(ev.error.message);setBusy(false);return;}await supabase.from("shipments").update({status:"delivered",delivered_at:now,destination_latitude:pos.coords.latitude,destination_longitude:pos.coords.longitude}).eq("id",s.id);await supabase.from("status_events").insert({shipment_id:s.id,status:"delivered",created_by:userId,latitude:pos.coords.latitude,longitude:pos.coords.longitude,note:"Ayuda entregada en el destino. Evidencia fotográfica registrada."});setMsg("Entrega confirmada con fotografía, fecha, hora y GPS.");await load();setBusy(false)},()=>{setMsg("Debes permitir la ubicación para confirmar la entrega.");setBusy(false)},{enableHighAccuracy:true});}
 if(!userId)return <div className="panel"><h1>Cargando panel...</h1></div>;
 return <div className="panel wide"><div className="row"><div><Link href="/">← Inicio</Link><h1>Panel operativo</h1></div><button className="btn btn-light" onClick={logout}>Cerrar sesión</button></div>
 {points.length===0?<div className="card"><h3>Aún no tienes un punto de acopio</h3><p>Registra el primer punto para comenzar a recibir y rastrear donaciones.</p><Link className="btn btn-primary" href="/registrar-acopio">Registrar punto</Link></div>:<>
 <div className="field point-select"><label>Punto de acopio</label><select value={pointId} onChange={e=>setPointId(e.target.value)}>{points.map(p=><option value={p.id} key={p.id}>{p.name} · {p.city}</option>)}</select></div><div className="notice">{point?.verified?"Punto verificado por la plataforma.":"Punto pendiente de verificación. Puedes operar, pero públicamente aparecerá como no verificado."}</div>
 {msg&&<div className="flash">{msg}</div>}
 <div className="kpis"><div className="kpi"><b>{batches.length}</b><span>Donaciones registradas</span></div><div className="kpi"><b>{shipments.filter(s=>s.status==="in_transit").length}</b><span>En tránsito</span></div><div className="kpi"><b>{shipments.filter(s=>s.status==="delivered").length}</b><span>Entregas verificadas</span></div><div className="kpi"><b>{expenses.length}</b><span>Comprobantes</span></div></div>
 <section className="dashboard-section"><h2>1. Registrar una donación</h2><p className="lead">Genera un código único para entregar al donante.</p><form className="card form-grid" onSubmit={createDonation}><div className="field"><label>Referencia del donante (opcional)</label><input name="donor_reference" placeholder="Nombre o referencia interna"/></div><div className="field"><label>Categoría</label><input name="category" required placeholder="Alimentos"/></div><div className="field"><label>Insumo</label><input name="item_name" required placeholder="Agua embotellada"/></div><div className="field"><label>Cantidad</label><input name="quantity" type="number" min="0.001" step="0.001" required/></div><div className="field"><label>Unidad</label><input name="unit" required placeholder="unidades, kg, cajas"/></div><div className="field"><label>Notas</label><input name="notes"/></div><div className="field full"><button className="btn btn-primary" disabled={busy}>Registrar y generar código</button></div></form>
 <div className="list card compact">{batches.slice(0,6).map(b=><div className="list-row" key={b.id}><span><b>{b.public_code}</b><br/><small>{new Date(b.received_at).toLocaleString("es-CO")}</small></span><Link className="btn btn-light" href={`/seguimiento/${b.public_code}`}>Ver seguimiento</Link></div>)}</div></section>
 <section className="dashboard-section"><h2>2. Inventario general</h2><form className="card form-grid" onSubmit={addInventory}><div className="field"><label>Categoría</label><input name="category" required/></div><div className="field"><label>Insumo</label><input name="item_name" required/></div><div className="field"><label>Cantidad disponible</label><input name="quantity" type="number" min="0" step="0.001" required/></div><div className="field"><label>Unidad</label><input name="unit" required/></div><div className="field full"><label>Notas</label><input name="notes"/></div><div className="field full"><button className="btn btn-primary" disabled={busy}>Agregar al inventario</button></div></form></section>
 <section className="dashboard-section"><h2>3. Compras y facturas</h2><form className="card form-grid" onSubmit={addExpense}><div className="field"><label>Descripción</label><input name="description" required/></div><div className="field"><label>Proveedor</label><input name="vendor_name"/></div><div className="field"><label>Valor COP</label><input name="amount" type="number" min="0" step="0.01" required/></div><div className="field"><label>Fecha de compra</label><input name="purchased_at" type="datetime-local"/></div><div className="field full"><label>Factura / comprobante</label><input name="invoice" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></div><div className="field full"><button className="btn btn-primary" disabled={busy}>Guardar comprobante</button></div></form></section>
 <section className="dashboard-section"><h2>4. Crear envío</h2><p className="lead">Vincula una donación para que su código público continúe mostrando el recorrido.</p><form className="card form-grid" onSubmit={createShipment}><div className="field"><label>Destino / comunidad</label><input name="destination_name" required/></div><div className="field"><label>Departamento</label><input name="destination_department" required/></div><div className="field"><label>Municipio</label><input name="destination_city" required/></div><div className="field"><label>Salida prevista</label><input name="departure_at" type="datetime-local"/></div><div className="field full"><label>Donación a vincular</label><select name="donation_item_id" defaultValue=""><option value="">Sin vincular por ahora</option>{donationItems.map(i=><option key={i.id} value={i.id}>{i.batch_code} · {i.item_name} ({i.quantity} {i.unit})</option>)}</select></div><div className="field full"><label>Cantidad de esa donación que viaja</label><input name="allocation_quantity" type="number" min="0.001" step="0.001" defaultValue="1"/></div><div className="field full"><button className="btn btn-primary" disabled={busy}>Crear envío</button></div></form></section>
 <section className="dashboard-section"><h2>5. Transporte y entrega</h2><div className="shipment-grid">{shipments.length===0&&<div className="card"><p>Aún no hay envíos.</p></div>}{shipments.map(s=><div className="card" key={s.id}><div className="row"><div><b>{s.public_code}</b><p>{s.destination_name}<br/>{s.destination_city}, {s.destination_department}</p></div><span className="tag">{statusLabel[s.status]||s.status}</span></div>{s.status==="ready"&&<button className="btn btn-primary" disabled={busy} onClick={()=>markDeparture(s)}>Registrar salida</button>}{s.status==="in_transit"&&<><div className="field"><label>Foto de la entrega</label><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>setDeliveryFiles(v=>({...v,[s.id]:e.target.files?.[0]||null}))}/></div><button className="btn btn-primary" disabled={busy} onClick={()=>deliver(s)}>Confirmar entrega con GPS</button></>}{s.status==="delivered"&&<Link className="btn btn-light" href={`/seguimiento/${s.public_code}`}>Ver evidencia pública</Link>}</div>)}</div></section>
 </>}</div>
}
